spring:
  datasource:
    master:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    slave:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    slave2:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
  jpa:
# ??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    RDS
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@cluster0.4ln8psb.mongodb.net/${MONGODB_DBNAME}?retryWrites=true&w=majority
